### ISSUE TITLE
class Estudiante inherits Usuario

### ISSUE THREAD

**Issue by alexmclm** [alexmclm/Grupo-08-PdeP#8]
el chiste de esta parte es poder ver si el usuario pueda elegir un transporte en base a su presupuesto
osea que los metodos empleados estan mal hechos
una forma mas facil es poder decir unTransporte . filter{(unTransporte=> self.tieneDineroSuficiente())}

es un bardo pero se puede tener una funcion asi

**Comment by MarcosDonner** [comment]
Arreglado!
